version: "3.8"
services:
  app:
    restart: always
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@db:5432/bigAppsTweets?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=YmVhdHNiYXNlNjQgYXNkZmFzZGZhc2RmYXNkZmFzZGY
      - DISCORD_CLIENT_ID=1205241465442406472
      - DISCORD_CLIENT_SECRET=bYRQpfIx6NcfrEyFeCQZE0HGqb4S6R
      - GOOGLE_ID=842836638449-ueud8f62oumod9jf60vifr9so6phce5d.apps.googleusercontent.com
      - GOOGLE_SECRET=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
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npx prisma db push && npm run dev"

  db:
    restart: always
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: bigAppsTweets

volumes:
  postgres_data:
